project_name: styx

builds:
  # Build styx-server
  -
    id: styx-server
    main: ./cmd/styx-server/main.go
    binary: styx-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

  # Build styx CLI
  -
    id: styx
    main: ./cmd/styx/main.go
    binary: styx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

nfpms:
  # Create packages
  -
    builds:
      - styx-server
      - styx

    vendor: Dataptive
    homepage: https://dataptive.io/
    maintainer: Thibaut Séguy <thibaut.seguy@gmail.com>
    description: Simple, high-performance event streaming platform

    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

    formats:
      - deb

    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh

    empty_folders:
      - /var/lib/styx
      - /var/run/styx

    contents:
      - src: config.linux.toml
        dst: /etc/styx/styx.toml
        type: config
      - src: scripts/styx.service
        dst: /lib/systemd/system/styx.service

# snapshot:
#   name_template: "{{ .Version }}"

archives:
  # Create release archives
  -
    builds:
      - styx-server
      - styx
    format: tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - LICENSE
      - config.toml

checksum:
  # Create release checksums
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

dockers:
  # Build and publish docker image
  -
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "dataptive/styx:latest"
      - "dataptive/styx:{{ .Version }}"
    extra_files:
      - config.toml

release:
  # Create release draft on github
  github:
    owner: dataptive
    name: styx

  draft: true